plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

dependencies {
    api "com.badlogicgames.gdx:gdx:$gdxVersion"

    testImplementation 'junit:junit:4.13.2'
}

// Les tests lisent les assets du jeu depuis le classpath.
sourceSets.test.resources.srcDirs += [rootProject.file('assets').path]
